name:                gopro
version:             0.1.0.0
github:              "dustin/gopro"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/gopro#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- text
- lens
- lens-aeson
- generic-deriving
- wreq
- time
- vector
- sqlite-simple
- mtl
- transformers
- optparse-applicative
- async
- qsem
- random
- extra
- monad-logger
- filepath
- scotty
- wai
- wai-middleware-static
- wai-extra
- unordered-containers

library:
  source-dirs: src
  ghc-options:
    - -Wall

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - NamedFieldPuns

executables:
  gopro:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
    - gopro

tests:
  gopro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gopro
    - HUnit
    - tasty
    - tasty-hunit
    - tasty-quickcheck
