name: "Nix Build"
on:
  workflow_dispatch:
  push:
    branches: [ master, amazonka2 ]
  schedule:
  - cron: "3 11 13,27 * *"
jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: dustin
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A gopro.components.exes.gopro
